### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by walterjamesperry**
Signed-off-by: Walter Perry <walterjamesperry@gmail.com>

### CODE REVIEW

**Review by LilianaRosado — APPROVED** [review]
Somebody once told me the world is gonna roll me
I ain't the sharpest tool in the shed
She was looking kind of dumb with her finger and her thumb
In the shape of an "L" on her forehead

**Comment by walterjamesperry** [comment]
login page was completed

**Comment by ccline29** [comment]
approval

**Comment by walterjamesperry** [comment]
log in page was completed

**Review by ccline29 — APPROVED** [review]

**Pull request merged**
